
name: cicdpipeline

on: [push]


jobs:
  test-python-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
    - name: Test python
      run: python hello.py

  build-python-script:
    needs: test-python-script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: hello-python
        path: ./hello.py
